### ISSUE TITLE
Where uploaded shell?

### ISSUE THREAD

**Issue by khushbakoff** [orionhridoy/cPanel-Karma#1]
![photo_2023-04-15_01-51-31](https://user-images.githubusercontent.com/72149974/232202449-53a72661-ab27-4166-8b97-885efa8f1197.jpg)

Shell uploaded it's good. But where uploaded? how will shell address? example: https://example.org:2083/shell.php? like this?

**Comment by orionhridoy** [comment]
You have to click on Shell Uploaded Button.
